- emc/interfaces/model.py
Starting to work towards generalization to *any* DIPY-compatible model.
> RF: Separate model initialization from fit/predict.

- eddymotion/dmri.py
Another FYI pull-request to cater to our tutorial.
> ENH: Allow passing in compression parameters in to_filename

- eddymotion/model.py
> RF: Use consistent names for DTI/DKI.

- README.md
Continuing towards fairly crediting our contributors :)
> ENH: Add zenodo badge to README

- eddymotion/model.py
Naive implementation of the AverageDWModel proposed in the nipreps-book. #41
> enh : Add regression to the mean model

- .github/workflows/contrib.yml
> MAINT: Reduce jobs in contrib GHA

- src/eddymotion/model.py
Rewrite the low-level parallelization of models.
> FIX: Stop using overly complicated asyncio for managing ThreadPoolExecutors

- src/eddymotion/estimator.py
Splits the modifications to the estimator from #91.
> ENH: Improvements to the estimator

- src/eddymotion/estimator.py
- src/eddymotion/model.py
This PR irons around the corners on top of #97.
> FIX: Revising parallel execution and related housekeeping

- .circleci/config.yml
> MAINT: Do not install ants with conda (CircleCI)

- src/eddymotion/estimator.py
- src/eddymotion/model.py
- Simplify implementation of new models
- Generate ``Full*`` models programmatically.
> ENH: Model building refactor

- src/eddymotion/data/dmri.py
- src/eddymotion/estimator.py
- src/eddymotion/model/__init__.py
- src/eddymotion/model/base.py
- src/eddymotion/viz.py
- test/test_dmri.py
- test/test_estimator.py
- test/test_integration.py
- test/test_model.py
With the expected sprawling modalities and models, we need to avoid very lengthy modules costly to maintain.
This PR is just a FYI to leave trace of the changes :)
> ENH: Refactor package structure

- src/eddymotion/data/pet.py
- src/eddymotion/estimator.py
- src/eddymotion/model/base.py
- src/eddymotion/viz.py
Miscellaneous documentation fixes:
- Fix paramater names in docstrings.
- Add missing parameters to docstrings.
- Remove non-existing arguments from docstrings.
- Fix grammar and typos.
> DOC: Miscellaneous documentation fixes

- README.rst
Add missing references in `README` file.
> DOC: Add missing references in `README` file

- test/test_estimator.py
Fix random seed in registration test for the sake of reproducibility.
> FIX: Set random seed in registration test

- src/eddymotion/model/base.py
Fix grammar in model factory docstring.
> DOC: Fix grammar in model factory docstring

- src/eddymotion/estimator.py
- test/test_integration.py
Rename estimator method to honor its purpose/use.
> STYLE: Rename estimator method to honor its purpose/use

- .github/workflows/pypi-package.yml
- pyproject.toml
https://github.com/nipreps/eddymotion/actions/runs/8850953249/job/24306415105 failed because of the local version.
> MNT: Drop local version to play nicely with test.pypi.org

- src/eddymotion/model/base.py
Fix typo in `ModelFactory` docstring.
> DOC: Fix typo in `ModelFactory` docstring

- src/eddymotion/data/dmri.py
- src/eddymotion/viz.py
Call the DWI plot method from its new location in `nireports`.
> ENH: Call the DWI plot method from nireports

- docs/developers.rst
- src/eddymotion/math/tests/test_utils.py
- src/eddymotion/math/utils.py
Add positive definite matrix check util method.
Add the corresponding test.
> ENH: Add positive definite matrix check util method

- src/eddymotion/estimator.py
Call the outsourced random volume index iterator in `estimator`.
> ENH: Call the outsourced random volume index iterator in `estimator`

- src/eddymotion/data/filtering.py
- DOC: Remove optional parameter values from docstring
- DOC: Use highlighting syntax for parameters and values
> DOC: Remove optional values in docstring

- test/test_data_utils.py
Set a seed for random number generation reproducibility in test. Use NumPy's `Generator` clas to generate random numbers.
Documentation:
https://numpy.org/doc/stable/reference/random/new-or-different.html
> STYLE: Set a seed for random number generation reproducibility

- src/eddymotion/model/base.py
Remove redundant `is_fitted` overrides in model classes.
> ENH: Remove redundant `is_fitted` overrides in model classes

- docs/notebooks/dmri_covariance.ipynb
Add dMRI covariance model notebook.
> ENH: Add dMRI covariance model notebook

- .circleci/config.yml
> MAINT: Install *ANTs* through conda (mamba)

- docs/developers.rst
- pyproject.toml
- src/eddymotion/viz/signals.py
Spins off work by @jhlegarreta in #227.
> ENH: Add a new ``eddymotion.viz`` module

- src/eddymotion/model/_dipy.py
- src/eddymotion/model/_sklearn.py
- src/eddymotion/registration/ants.py
- src/eddymotion/testing/simulations.py
- DOC: Miscellaneous docstring fixes in model module
- DOC: Miscellaneous improvements to comments
- STYLE: Increase consistency in function parameter order
> DOC: Miscellaneous docstring fixes

- docs/notebooks/dmri_covariance.ipynb
- scripts/dwi_gp_estimation_error_analysis.py
- scripts/dwi_gp_estimation_simulated_signal.py
- src/eddymotion/estimator.py
- src/eddymotion/model/_dipy.py
- src/eddymotion/model/gpr.py
- test/test_gpr.py
* rename the module so that it is picked up by autodoc.
* also fixes minor errors and improves docs.
> ENH: Rename ``eddymotion._sklearn`` -> ``eddymotion.gpr``
