- emc/config/dwi-to-b0_level1.json
- emc/config/dwi-to-dwi_level1.json
- emc/config/registration.json
- emc/dmri.py
- emc/estimator.py
- emc/model.py
Setting some foundations for the code:
- The DWI object to encapsulate inputs (please let me know if it encloses all we will possibly need).
- Stubb to start building the core of the implementation, defining some sort of API.
UPDATE:
This is how it looks right now:
```Python
>>> from emc import dmri
>>> from emc.estimator import EddyMotionEstimator
>>> data = dmri.load(
...     "ds001771/sub-36/dwi/sub-36_acq-AP_dwi.nii.gz",
...     gradients_file="rasb.tsv",
...     b0_file="sub-36_acq-PA_dwi_b0_mcf_ref.nii.gz",
...     brainmask_file="mask.nii.gz"
...     )
>>> EddyMotionEstimator.fit(data, model="b0")
Processing b-index <19> in </var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/tmpedeh8iiv>
Processing b-index <35> in </var/folders/l9/0lkn3g4s27bgkk75n6jj778r0000gp/T/tmppb9tb2cz> …
```
> ENH: Nipype-less implementation (refactor)

- src/eddymotion/model.py
- test/conftest.py
- test/test_estimator.py
- test/test_integration.py
- test/test_model.py
- test/test_version.py
Although this is not going to make all tests to pass, it at least ensures tests can be executed provided with test data fount under ``$TEST_DATA_HOME``.
This PR also fixes a bug on the ``AverageDWModel`` that resulting in the indexing error.
> FIX: Miscelaneous revisions to make tests execute properly

- src/eddymotion/dmri.py
This has been a sneaky one.
When directly generating the default value, ``mkdtemp()`` was executed only once, so all ``DWI`` objects created within the same scope pointed at the same path.
Resolves: #86.
> FIX: Generate temporary H5 cache path anew with every new instance of ``DWI``

- test/test_integration.py
Drops the use of a real AFNI series of transforms. Instead, generate a number of large-yet-plausible transformations for head motion.
I have visually checked a few things:
- NiTransforms correctly generates the dataset with motion, and when *realigining* it with the originally created transforms, indeed the dataset does not show any motion (uncomment line writing out `ground_truth.nii.gz` to see). Meaning, NiTransforms seems to be a reliable tool for this test.
- The correction by our estimator is ATM not great, but we are just testing the integration of all pieces (see #40 for comments on fine-tuning).
Follow-up: #84.
Part-of: #40.
> FIX: Integration test with B0 (trivial) model

- src/eddymotion/config/dwi-to-b0_level1.json
- src/eddymotion/config/dwi-to-dwi_level1.json
- src/eddymotion/dmri.py
- test/test_dmri.py
- test/test_estimator.py
This PR revises the data loading:
- Add the possibility to read FSL's bvec/bval files for building the gradient table
- Remove reorientations of the data (still thinking why they were there in the first place)
- Calculating a b=0 map if none is provided
> FIX: Housekeeping of the data loader function

- src/eddymotion/estimator.py
- src/eddymotion/model.py
The idea behind this model (credit goes to @tmspvn) is to only fit the DKI model once, which could be useful (and, importantly, way faster) for a first pass of head-motion correction.
This new model fits the DKI model at instantiation time, before entering the LOGO loop. Then, the ``predict()`` member just returns the map corresponding to the requested gradient (bvec/bval).
Therefore, it does some "double-dipping" in the sense that the gradient being predicted has already been "seen" in training. The model is likely degraded by the fact that the data are not aligned.
I will keep you updated (cc/ @yasseraleman).
> ENH: Add ``FullDKIModel''

- .github/workflows/pythonpackage.yml
- setup.cfg
Although Python 3.7 end-of-life is set for in 6 months (Jun 27, 2023), scikit-learn does not support it as of 1.8.0 (which will become the minimal version with #161).
I belive discontinuing Python 3.7 at this point is better than implementing the bspline matrix ourselves.
> MAINT: Pin Python >= 3.8

- docs/conf.py
- BUG: Specify the language in Sphinx documentation config file
- BUG: Fix DIPY doc URL in Sphinx documentation config file
> BUG: Fix Sphinx documentation configuration file

- .github/workflows/docs-build-pr.yml
- .github/workflows/docs-build-update.yml
- docs/requirements.txt
Remove unnecessary `docs/requirements.txt`: documentation dependencies are listed in the `[doc]` section of the `pyproject.toml` file.
Use the `pip install .[doc]` command to install the package dependencies, including the documentation packages, in the GitHub workflow files.
> ENH: Remove unnecessary `docs/requirements.txt`

- .github/workflows/docs-build-update.yml
Fix GitHub workflow actions warnings linked to `Node.js`: bump
`actions/checkout`.
Fixes:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v2. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
and
```
The following actions uses node12 which is deprecated and will be forced to run on node16:
actions/checkout@v2. For more info:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
raised for example in:
https://github.com/nipreps/eddymotion/actions/runs/8375229804
> ENH: Fix GitHub workflow actions warnings linked to `Node.js`

- src/eddymotion/estimator.py
Avoid using `pytest` `tmpdir` fixture as variable name: rename the variable.
Fixes:
```
Fixture 'tmpdir' is not requested by test functions or @pytest.mark.usefixtures marker
```
> ENH: Avoid using `pytest` `tmpdir` fixture as variable name

- .github/workflows/contrib.yml
- pyproject.toml
- src/eddymotion/data/dmri.py
- src/eddymotion/model/base.py
- src/eddymotion/viz.py
- Replace flake8 CI job with a ruff CI job.
> CI: replace flake8 by ruff check

- pyproject.toml
Add Python 3.12 to project classifiers. Python 3.12 was introduced in commit d27a448.
> ENH: Add Python 3.12 to project classifiers

- README.rst
- DOC: Add status badges to `README` file
- DOC: Make `README` refs be considered as citations instead of footnotes
- DOC: Use URL as path to static content in `README`
> DOC: Add status badges to `README` file

- src/eddymotion/data/dmri.py
- src/eddymotion/data/pet.py
Remove unused parameter from method prototype: PET images do not have a `b0` image. Use the `*_` to denote unused arguments for the `PET` class and use a `kwargs` dictionary for the `DWI` case.
> ENH: Remove unused parameter from method prototype

- src/eddymotion/model/base.py
Define instance attributes in `__init__` method.
Fixes:
```
Instance attribute _datashape defined outside __init__
```
and similar warnings.
> ENH: Define instance attributes in `__init__` method

- src/eddymotion/estimator.py
Use NumPy's `Generator` class as a replacement for `RandomState` for random variarte generation methods.
`RandomState` was deprecated in NumPy 1.17.0.
Take advantage of the commit to document better the use of the `seed` parameter.
Documentation:
https://numpy.org/doc/stable/reference/random/new-or-different.html#what-s-new-or-different
https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html
> ENH: Use NumPy's `Generator` class as a replacement for `RandomState`

- .github/workflows/contrib.yml
- .pre-commit-config.yaml
- docs/conf.py
- pyproject.toml
- test/test_dmri.py
Refactor code linter and formatter dependencies:
- Remove `black`, `flake8` and `isort` dependencies from `pyproject.toml`: the role has been taken over by `ruff` in commit 81b3690.
- Transfer the `black` and `isort` rules left behind to `ruff` in `pyproject.toml`
- Remove `black`, `flake8` and `isort` from the pre-commit config file and use `ruff` instead.
> ENH: Refactor code linter and formatter dependencies

- .github/workflows/contrib.yml
- .maint/paper_author_list.py
- .maint/update_zenodo.py
- src/eddymotion/__init__.py
- src/eddymotion/data/dmri.py
- src/eddymotion/data/pet.py
- src/eddymotion/estimator.py
- src/eddymotion/model/__init__.py
- src/eddymotion/model/base.py
- src/eddymotion/viz.py
- test/conftest.py
- test/test_estimator.py
- test/test_integration.py
- test/test_model.py
- test/test_version.py
Format the code base style.
Add the corresponding command to the contribution checks GitHub Actions workflow so that the differences that need to be applied are actually shown on GitHub.
> STYLE: Format the code base style

- pyproject.toml
- src/eddymotion/estimator.py
Simplify `eddymotion.estimator.EddyMotionEstimator.fit`: break down different parts into separate methods.
Fixes:
```
src/eddymotion/estimator.py:43:9: C901 `fit` is too complex (23 > 10)
```
raised by `ruff`.
Remove the `C901` error exception rule from the `ruff` linter whitelist.
Fixes #142.
> ENH: Simplify `eddymotion.estimator.EddyMotionEstimator.fit`

- src/eddymotion/data/dmri.py
- src/eddymotion/data/splitting.py
- src/eddymotion/estimator.py
- test/test_model.py
- test/test_splitting.py
(Empty message edited by @oesteban)
This PR covers two targets:
> ENH: Outsource leave-one-out splitter so it can be used across data types

- src/eddymotion/data/splitting.py
- test/test_model.py
- test/test_splitting.py
Remove style errors introduced by PR merge.
closes #151
> STY: fix style errors

- README.rst
Add CircleCI status badge to README so that the status of the package testing is known.
> DOC: Add CircleCI status badge to README

- test/test_integration.py
Remove unused `tmp_path` parameter from test.
> ENH: Remove unused `tmp_path` parameter from test

- src/eddymotion/estimator.py
Remove unnamed return parameter from `EddyMotionEstimator` class docstring.
> DOC: Remove unnamed return parameter from docstring

- .circleci/config.yml
- .github/workflows/pythonpackage.yml
- pyproject.toml
Drop support for Python 3.8 and 3.9: require Python 3.10 or greater in line with Scientific Python SPEC 0:
https://scientific-python.org/specs/spec-0000/
Remove them from the CI matrices.
Use CircleCI's docker image so that the pacakge gets tested on Python 3.10:
https://hub.docker.com/u/cimg
Resolves #140.
> ENH: Drop support for Python 3.8 and 3.9

- .maint/update_authors.py
Require the iterables in a `zip` call to have equal length.
Fixes:
```
installing ruff...
--- .maint/update_authors.py
+++ .maint/update_authors.py
@@ -49,7 +49,7 @@
break
values = [v.strip() or None for v in line.split("|")][1:-1]
-        retval.append({k: v for k, v in zip(keys, values) if v})
+        retval.append({k: v for k, v in zip(keys, values, strict=False) if v})
return retval
@@ -288,7 +288,7 @@
print("Authors (%d):" % len(hits))
print(
"%s."
-        % "; ".join(["%s \\ :sup:`%s`\\ " % (i["name"], idx) for i, idx in zip(hits, aff_indexes)])
+        % "; ".join(["%s \\ :sup:`%s`\\ " % (i["name"], idx) for i, idx in zip(hits, aff_indexes, strict=False)])
)
print(
Would fix 2 errors.
```
raised for example in:
https://github.com/nipreps/eddymotion/actions/runs/8707149384/job/23 …
> ENH: Require the iterables in a zip call to have equal length

- .circleci/config.yml
Bump CircleCI docker image.
Fixes:
```
ERROR: Package 'eddymotion' requires a different Python: 3.9.12 not in '>=3.10'
```
raised for example in:
https://app.circleci.com/pipelines/github/nipreps/eddymotion/978/workflows/62e30eb5-72ed-4cf9-8b47-0172cad51228/jobs/951
> ENH: Bump CircleCI docker image

- README.rst
Use img shields license badge (rather than relying on PyPI) and point to file (rather than to PyPI).
> ENH: Use img shields license badge and point to file

- src/eddymotion/data/dmri.py
- test/test_dmri.py
- BUG: Do not pass the nibabel instance variable to `get_fdata`
- ENH: Implement DWI equality explicitly
Resolves #95.
> ENH: Implement DWI equality explicitly

- src/eddymotion/math/tests/test_utils.py
- src/eddymotion/math/utils.py
- src/eddymotion/model/gradient_utils.py
- src/eddymotion/model/tests/test_gradient_utils.py
Add gradient encoding direction angle computation utils: compute pairwise angles across gradient encoding directions.
Add the corresponding test.
> ENH: Add gradient encoding direction angle computation utils

- src/eddymotion/exceptions.py
Fix `ModelNotFitterError` class docstring to honor its purpose.
> DOC: Fix `ModelNotFitterError` class docstring

- src/eddymotion/model/base.py
- test/test_model.py
Make models inherit from base model.
> ENH: Make models inherit from base model

- src/eddymotion/model/gradient_utils.py
- src/eddymotion/model/tests/test_gradient_utils.py
Make the gradient vector computation method accept two input parameters: instead of compute the angles across vectors in a single array, accept two input parameters and compute the angles across the vectors in them.
This change is introduced following the discussions on the kernel used for the Gaussian process requiring two inputs.
Take advantage of the commit to parameterize the testing and add more test cases.
Reword the comments in the testing for the sake of clearliness.
> ENH: Make grad vec angle computation method accept two input parameters

- .github/workflows/test.yml
- env.yml
- test/test_integration.py
- tox.ini
Revises the GHA migration to make sure that tests run:
- Added dataset download using datalad (as it was the case in Circle)
- Improved the tox config to ensure environment variables are considered
- Added execution of pytest on the `test/` folder.
- Does not test on a matrix of pythons because the python version should not introduce differences (to consider when we have code where it could be a problem).
IMHO, the addition of tox deviates from other projects (and as far as I understand, we were not planning on using tox) and has introduced some complexity. In particular, I had to set one test to skip because of (I suspect) some minimal environment change tox introduces.
For now, I wanted to focus on the download of data and execution of all tests. Future PRs can address the removal of …
> MAINT: Revision of GHA migration

- .github/workflows/test.yml
- pyproject.toml
- tox.ini
Adopt `tox` for testing environment configuration as per decision at the Oct 1 2024 Technical Monitoring meeting.
Add the necessary `tox.ini` file and edit the GHA `test.yml` workflow file to use `tox`, to use `ants`, to use `DataLad` to download the testing data, and to cache the data across the build matrix.
Pin `nitransforms` to <24 following commit d26541b. The decision on pinning to <24 was made following consistent failures on `test_proximity_estimator_trivial_model`, e.g.
https://github.com/nipreps/eddymotion/actions/runs/11123784605/job/30907972182#step:8:196
and
https://github.com/nipreps/eddymotion/actions/runs/11203922080/job/31141711676?pr=234#step:12:342
The version was pinned for the conda `env.yml` config file, but not `pyproject.toml`.
> MAINT: Adopt `tox` for testing environment configuration

- LICENSE
- NOTICE
- scripts/optimize_registration.py
- src/eddymotion/__main__.py
- src/eddymotion/cli/parser.py
- src/eddymotion/cli/run.py
- src/eddymotion/conftest.py
- src/eddymotion/exceptions.py
- src/eddymotion/math/tests/test_utils.py
- src/eddymotion/math/utils.py
- src/eddymotion/model/_dipy.py
- src/eddymotion/model/dmri.py
- src/eddymotion/registration/ants.py
- src/eddymotion/registration/utils.py
- src/eddymotion/utils.py
- test/conftest.py
- test/test_dipy.py
- test/test_dmri.py
- test/test_integration.py
- test/test_main.py
- test/test_model.py
- test/test_parser.py
- test/test_splitting.py
- test/test_version.py
Improve the copyright notice information in the `LICENSE` file: make the notice specific to this repository and avoid any variability in the notices by removing the placeholders:
- Use the original year (2021) in which works were first released.
- Use the NiPreps name and email address in `LICENSE` file.
- Remove the explanation related to the placeholders.
Apply the above changes to the copyright notices across source files.
> DOC: Improve the copyright notice information in the `LICENSE` file

- docs/developers.rst
- pyproject.toml
- src/eddymotion/testing/simulations.py
Brings @jhlegarreta's code from #227.
> ENH: Add a testing module to keep convenience tooling

- src/eddymotion/model/_dipy.py
- src/eddymotion/model/_sklearn.py
- test/test_model.py
- test/test_sklearn.py
> ENH: Refactor of GP regression models

- src/eddymotion/model/_dipy.py
- src/eddymotion/model/_sklearn.py
- src/eddymotion/testing/simulations.py
- src/eddymotion/viz/signals.py
Prefer using "Copyright" over the symbol in file headers.
> STYLE: Prefer using "Copyright" over the symbol in file headers

- src/eddymotion/testing/simulations.py
Allow simulating multi-fiber voxels.
> ENH: Allow simulating multi-fiber voxels

- scripts/dwi_gp_estimation_error_analysis.py
- scripts/dwi_gp_estimation_error_analysis_plot.py
- scripts/dwi_gp_estimation_signal_plot.py
- scripts/dwi_gp_estimation_simulated_signal.py
- ENH: Miscellaneous improvements to the scripts
- ENH: Compute the number of CV repetitions dynamically
- DOC: Improve consistency in script function docstring
> ENH: Miscellaneous improvements to the scripts

- scripts/dwi_gp_estimation_error_analysis.py
Moves to optional many arguments so that the script is easier to call (previously, you needed to check the right ordering always and positional parameters are very easy to mix-up).
It also makes optional several features: writing the generated synthetic data, writing the predictions, and the k-fold cross validation (added a single-run possibility useful for debugging).
> ENH: Improve CLI of the dwi/error experiment

- README.rst
- docs/index.rst
Fix cut passages from `README` in documentation index file: add comments around the flowchart image in the `README` file and change the `start-line` and `end-line` directive pair for the `end-before` and `start-after` pair to skip the flowchart image only.
The `start-line` and `end-line` directives were making such that relevant passages of the `README` file providing context for the tool were not being included. Thus the text shown in the documentation index file had some missing parts, and was not making sense.
> DOC: Fix cut passages from `README` in documentation index file

- docs/conf.py
- src/eddymotion/model/gpr.py
Add `__init__` documentation to class documentation:
- Add a function to the documentation configuration file that processes the signatures and adds the `__init__` method signature to the class signatures.
- Make the class documentation contain the documentation from both the class and the `__ini__` method setting the `autoclass_content` option to `both`.
Remove the short description of the `__init__` methods so that the class documentation reads seamlessly.
> DOC: Add `__init__` documentation to class documentation

- src/eddymotion/model/gpr.py
- DOC: Fix typos in GPR model documentation
- DOC: Expand GP acronym when introduced for the first time in GPR model
- DOC: Prefer impersonal style in `EddyMotionGPR` hpm optimization comment
- DOC: Do not introduce unnecessary line breaks within paragraph
- DOC: Use literal highlighting syntax for `a` parameter
- DOC: Use obj Sphinx role to reference `NumPy` arrays consistently
> DOC: Miscellaneous `gpr` module documentation fixes

- src/eddymotion/model/gpr.py
Make Kriging hyperparameter property naming consistent: use `hyperparameter_l` instead of `hyperparameter_beta_l` for the `beta_l` hyperparameter, much like `hyperparameter_a` is being used for the `beta_a` hyperparameter.
> STYLE: Make Kriging hyperparameter property naming consistent

- docs/installation.rst
Fix installation documentation Python version: the tool supports Python greater than or equal to 3.10.
> DOC: Fix installation documentation Python version
